Better error handling

diff --git a/bin/gvm b/bin/gvm
--- a/bin/gvm
+++ b/bin/gvm
@@ -8,6 +8,12 @@ if [ -z "$GVM_ROOT" ]; then
   exit 1
 fi
 
+$GVM_ROOT/bin/gvm-check
+if [[ "$?" != "0" ]]; then
+  echo "ERROR: Missing requirements. Please see messages above"
+  exit 1
+fi
+
 if [[ $1 == "version" ]]; then
   echo "Go Version Manager v$GVM_VERSION"
 elif [[ $1 == "implode" ]]; then
