Require GVM_ROOT to be set in order to run gvm commands.

diff --git a/bin/gvm b/bin/gvm
--- a/bin/gvm
+++ b/bin/gvm
@@ -1,4 +1,13 @@
 #!/bin/bash
+if [ -z "$GVM_ROOT" ]; then
+  echo 'ERROR: $GVM_ROOT is not set! Please update your .bashrc or .profile to $
+
+  [[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
+
+  '
+  exit 1
+fi
+
 if [[ $1 == "version" ]]; then
   echo "Go Version Manager v$GVM_VERSION"
 elif [[ $1 == "implode" ]]; then
