gvm pkg install is complete!

diff --git a/bin/gvm-install b/bin/gvm-install
--- a/bin/gvm-install
+++ b/bin/gvm-install
@@ -112,10 +112,29 @@ create_default_pkgset() {
 
 install_gb() {
   echo " * Installing gb..."
-  goinstall github.com/skelterjohn/go-gb/gb  
+  goinstall github.com/skelterjohn/go-gb/gb
   if [[ $? -ne 0 ]]; then
     echo "Failed to install gb"
     exit 1
+  fi
+}
+
+install_goprotobuf() {
+  echo " * Installing goprotobuf..."
+  if [[ "$SOURCE_TAG" == "release.r60.3" ]]; then
+    goinstall goprotobuf.googlecode.com/hg/proto
+    if [[ $? -ne 0 ]]; then
+      echo "Failed to install goprotobuf"
+      exit 1
+    fi
+    cd $GOROOT/src/pkg/goprotobuf.googlecode.com/hg/compiler
+    make install > $GVM_ROOT/logs/$SOURCE_TAG-pb-compiler.log 2>&1
+    if [[ $? -ne 0 ]]; then
+      echo "Failed to install goprotobuf compiler"
+      exit 1
+    fi
+  else
+    echo "   Don't know how to install goprotobuf for $SOURCE_TAG"
   fi
 }
 
@@ -123,6 +142,7 @@ main() {
   setup_install_env
   compile
   install_gb
+  install_goprotobuf
   create_default_pkgset
 }
 
diff --git a/bin/gvm-pkg-uninstall b/bin/gvm-pkg-uninstall
--- a/bin/gvm-pkg-uninstall
+++ b/bin/gvm-pkg-uninstall
@@ -1,13 +1,31 @@
 #!/bin/bash
 if [[ $1 == "pkg" ]] && [[ $2 == "uninstall" ]]; then
-  UNINSTALL_ROOT=$GVM_ROOT/pkgs/default/$3-$4
-  if [[ -n $4 ]]; then
-    rm -rf $UNINSTALL_ROOT
-    echo "Uninstalled $3 version $4"
-    exit 0
-  else
-    echo "ERROR: Please specifiy the name and version"
+  if [[ "$3" == "" ]]; then
+    echo "ERROR: Please specify the package name"
     exit 1
+  fi
+
+  UNINSTALL_ROOT=$GVM_ROOT/pkgs/pkg.gvm/$3
+  if [[ ! -d $UNINSTALL_ROOT ]]; then
+    echo "ERROR: Invalid package name"
+    exit 1
+  fi
+
+  if [[ "$4" != "" ]]; then
+    UNINSTALL_ROOT=$UNINSTALL_ROOT/$4
+  fi
+
+  if [[ -d $UNINSTALL_ROOT ]]; then
+    rm -rf $UNINSTALL_ROOT
+  else
+    echo "ERROR: Invalid package version"
+    exit 1
+  fi
+
+  if [[ "$4" != "" ]]; then
+    echo "Uninstalled $3 version $4"
+  else
+    echo "Uninstalled $3"
   fi
 else
   echo "Please use gvm [action] to call this file"
