Ditch the go- prefix. Make sure version exists in the use and uninstall commands.

diff --git a/bin/gvm-uninstall b/bin/gvm-uninstall
--- a/bin/gvm-uninstall
+++ b/bin/gvm-uninstall
@@ -1,9 +1,14 @@
 #!/bin/bash
-UNINSTALL_ROOT=$GVM_ROOT/gos/go-$2
+UNINSTALL_ROOT=$GVM_ROOT/gos/$2
 if [[ $1 == "uninstall" ]]; then
   if [[ -n $2 ]]; then
-    rm -rf $UNINSTALL_ROOT
-    echo "Uninstalled version $2"
+    if [ -d $UNINSTALL_ROOT ]; then
+      rm -rf $UNINSTALL_ROOT
+      echo "Uninstalled version $2"
+    else
+      echo "Invalid version"
+      exit 1
+    fi
     exit 0
   else
     echo "ERROR: Please specifiy the version"
diff --git a/bin/gvm-use b/bin/gvm-use
--- a/bin/gvm-use
+++ b/bin/gvm-use
@@ -1,12 +1,17 @@
 #!/bin/bash
 if [[ $1 == "use" ]]; then
   if [[ -n $2 ]]; then
-    rm -f $GVM_ROOT/gos/default
-    ln -s $GVM_ROOT/gos/go-$2 $GVM_ROOT/gos/default
-    rm -f $GVM_ROOT/pkgs/default
-    ln -s $GVM_ROOT/pkgs/go-$2 $GVM_ROOT/pkgs/default
-    echo "Now using version $2"
-    exit 0
+    if [ -d $GVM_ROOT/gos/$2 ]; then
+      rm -f $GVM_ROOT/gos/default
+      ln -s $GVM_ROOT/gos/$2 $GVM_ROOT/gos/default
+      rm -f $GVM_ROOT/pkgs/default
+      ln -s $GVM_ROOT/pkgs/$2 $GVM_ROOT/pkgs/default
+      echo "Now using version $2"
+      exit 0
+    else
+      echo "Invalid version"
+      exit 1
+    fi
   else
     echo "ERROR: Please specifiy the version"
     exit 1
