Allow gvm use shorthand

diff --git a/bin/gvm-use b/bin/gvm-use
--- a/bin/gvm-use
+++ b/bin/gvm-use
@@ -1,15 +1,20 @@
 #!/bin/bash
 if [[ $1 == "use" ]]; then
   if [[ -n $2 ]]; then
-    if [ -d $GVM_ROOT/gos/$2 ]; then
+    fuzzy_match=`ls $GVM_ROOT/gos | grep "$2"`
+    if [[ $? != 0 ]]; then
+      echo "Invalid version $2"
+      exit 1
+    fi
+    if [ -d $GVM_ROOT/gos/$fuzzy_match ]; then
       rm -f $GVM_ROOT/go
-      ln -s $GVM_ROOT/gos/$2 $GVM_ROOT/go
+      ln -s $GVM_ROOT/gos/$fuzzy_match $GVM_ROOT/go
       rm -f $GVM_ROOT/pkgs
-      ln -s $GVM_ROOT/pkgsets/$2/default $GVM_ROOT/pkgs
-      echo "Now using version $2"
+      ln -s $GVM_ROOT/pkgsets/$fuzzy_match/default $GVM_ROOT/pkgs
+      echo "Now using version $fuzzy_match"
       exit 0
     else
-      echo "Invalid version"
+      echo "Invalid version $2"
       exit 1
     fi
   else
