Fuzzy match for uninstall

diff --git a/bin/gvm-uninstall b/bin/gvm-uninstall
--- a/bin/gvm-uninstall
+++ b/bin/gvm-uninstall
@@ -1,10 +1,14 @@
 #!/bin/bash
-UNINSTALL_ROOT=$GVM_ROOT/gos/$2
 if [[ $1 == "uninstall" ]]; then
   if [[ -n $2 ]]; then
-    if [ -d $UNINSTALL_ROOT ]; then
-      rm -rf $UNINSTALL_ROOT
-      echo "Uninstalled version $2"
+    fuzzy_match=`ls $GVM_ROOT/gos | grep "$2"`
+    if [[ $? != 0 ]]; then
+      echo "Invalid version $2"
+      exit 1
+    fi
+    if [ -d $GVM_ROOT/gos/$fuzzy_match ]; then
+      rm -rf $GVM_ROOT/gos/$fuzzy_match
+      echo "Uninstalled version $fuzzy_match"
     else
       echo "Invalid version"
       exit 1
