Adding binutils check

diff --git a/bin/gvm-check b/bin/gvm-check
--- a/bin/gvm-check
+++ b/bin/gvm-check
@@ -4,3 +4,7 @@ if [ -z `which hg` ]; then
   exit 1
 fi
 
+if [ -z `ar` ]; then
+  echo '* Could not find binutils (try `sudo apt-get install binutils (or binutils-multiarch)`)'
+  exit 1
+fi
