Cleaned up

diff --git a/bin/gvminstall b/bin/gvminstall
--- a/bin/gvminstall
+++ b/bin/gvminstall
@@ -1,31 +1,51 @@
 #!/bin/bash
-tmp_dir=/tmp/gvm/$1
+cache_dir=$GVM_ROOT/pkg-cache/$1
+source_dir=/tmp/gvm/$1/src
+build_dir=/tmp/gvm/$1/build
 package_name=$1
+version=$2
 
 function download_package() {
-	#echo "Installing $package_name..."
-	if [ ! -d "$tmp_dir/src" ]; then
-		mkdir -p $tmp_dir/src
-		git clone git@github.com:moovweb/$1 $tmp_dir/src > /dev/null 2>&1
+	if [ ! -d "$cache_dir" ]; then
+		echo "Downloading $package_name..."
+		mkdir -p $cache_dir
+		git clone git@github.com:moovweb/$package_name $cache_dir > /dev/null 2>&1
 		if [[ $? -ne 0 ]]; then
-			echo "Could not find $1 in any sources"
-			exit 1
-		fi
-	fi
-	if [ "$2" != "" ]; then
-		cd $tmp_dir/src &&
-		git checkout $2 > /dev/null 2>&1
-		if [[ $? -ne 0 ]]; then
-			echo "Invalid version $2"
+			echo "ERROR: Could not find $package_name in any sources"
 			exit 1
 		fi
 	fi
 }
 
+function select_version() {
+	if [ "$version" != "" ]; then
+		cd $source_dir && git pull &&
+		git checkout $version > /dev/null 2>&1
+		if [[ $? -ne 0 ]]; then
+			echo "Invalid version $version"
+			exit 1
+		fi
+	fi
+}
+
+function setup_build_env() {
+	rm -rf $build_dir && mkdir -p $build_dir
+	rm -rf $source_dir && mkdir -p $source_dir
+	cp -r $cache_dir/* $source_dir
+	#if [[ -n $BUILD_NUMBER ]]; then
+	#  export BUILD_NUMBER="`cat VERSION`.$BUILD_NUMBER"
+	#else
+		export BUILD_NUMBER="`cat $source_dir/VERSION`.dev"
+	#fi
+
+	echo "$BUILD_NUMBER" > $build_dir/BUILD_VERSION
+	select_version
+}
+
 function check_deps() {
-	export GOPATH=$tmp_dir/build
-	if [ -f "Package.gvm" ]; then
-		for line in `cat Package.gvm | grep ^pkg | awk '{ print $2 }'`; do
+	export GOPATH=$build_dir
+	if [ -f "$source_dir/Package.gvm" ]; then
+		for line in `cat $source_dir/Package.gvm | grep ^pkg | awk '{ print $2 }'`; do
 			CUR_PKG=$GVM_ROOT/pkgs/$line/current
 			if [ -e "$CUR_PKG/BUILD_VERSION" ]; then
 				#echo "Using: $line (`cat $CUR_PKG/BUILD_VERSION`)";
@@ -45,27 +65,18 @@ function check_deps() {
 }
 
 function build_package() {
-	cd $tmp_dir/src
-	mkdir -p $tmp_dir/build
-	#if [[ -n $BUILD_NUMBER ]]; then
-	#  export BUILD_NUMBER="`cat VERSION`.$BUILD_NUMBER"
-	#else
-		export BUILD_NUMBER="`cat VERSION`.dev"
-	#fi
-
-	echo "$BUILD_NUMBER" > $tmp_dir/build/BUILD_VERSION
-
-	check_deps
-
 	echo "Installing $package_name..."
-	cd $tmp_dir/src && gvmake > /dev/null 2>&1
+	cd $source_dir && gvmake > $build_dir/build.log 2>&1
 	if [ $? -ne 0 ]; then
 		echo "ERROR: Failed to build"
+		cat "$build_dir/build.log"
 		exit 1
 	fi
-	
+}
+
+function install_package() {
 	mkdir -p $GVM_ROOT/pkgs/$package_name/$BUILD_NUMBER &&
-	cp $tmp_dir/build/* $GVM_ROOT/pkgs/$package_name/$BUILD_NUMBER -r &&
+	cp $build_dir/* $GVM_ROOT/pkgs/$package_name/$BUILD_NUMBER -r &&
 	rm -f $GVM_ROOT/pkgs/$package_name/current &&
 	ln -s $GVM_ROOT/pkgs/$package_name/$BUILD_NUMBER $GVM_ROOT/pkgs/$package_name/current &&
 	if [ $? -ne 0 ]; then
@@ -73,12 +84,15 @@ function build_package() {
 		exit 1
 	fi
 
-	if [ -d $tmp_dir/build/bin ]; then
+	if [ -d $build_dir/bin ]; then
 		mkdir -p $GVM_ROOT/pkgs/bin &&
-		cp -f $tmp_dir/build/bin/* $GVM_ROOT/pkgs/bin/
+		cp -f $build_dir/bin/* $GVM_ROOT/pkgs/bin/
 	fi
 }
 
-download_package $package_name $2
+download_package
+setup_build_env
+check_deps
 build_package
+install_package
 
