Print errors to stderr

diff --git a/scripts/env/use b/scripts/env/use
--- a/scripts/env/use
+++ b/scripts/env/use
@@ -1,7 +1,7 @@
 function display_error() {
 	tput sgr0
 	tput setaf 1
-	echo "ERROR: $1"
+	echo "ERROR: $1" >&2
 	tput sgr0
 	return 1
 }
