All that's left is to make a tag or branch for stable

diff --git a/binscripts/gvm-installer b/binscripts/gvm-installer
--- a/binscripts/gvm-installer
+++ b/binscripts/gvm-installer
@@ -1,4 +1,5 @@
 #!/bin/bash
+BRANCH=$1
 if [ "$(whoami)" != "root" ]; then
 	GVM_DEST=~
 	GVM_NAME=.gvm
@@ -14,26 +15,34 @@ if [ -d $GVM_DEST/$GVM_NAME ]; then
   echo "Already installed!"
 else
   cd $GVM_DEST && git clone $SRC_REPO $GVM_NAME > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+    echo "Failed to clone from $SRC_REPO into $GVM_DEST/$GVM_NAME"
+    exit 1
+  fi
+  if [ "$BRANCH" == "stable" ]; then
+    cd $GVM_DEST && git checkout $BRANCH > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+      echo "Failed to checkout $BRANCH branch"
+      exit 1
+    fi
+  fi
   rm -rf $GVM_DEST/$GVM_NAME/.git
-	if [ "$1" == "stable" ]; then
-		echo "Installing stable"
-	fi
-	if [ "$(whoami)" != "root" ]; then
-		if [ -e ~/.bashrc ]; then
-		  cat ~/.bashrc | grep "\[\[ -s \"\$HOME/.gvm/scripts/gvm\" ]] && source \"\$HOME/.gvm/scripts/gvm\"" > /dev/null 2>&1
-		  if [ $? -ne 0 ]; then
-		    echo '[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"' >> $ENV_FILE
-		  fi
-		else
-		  echo 'This must be a Mac... put this line in you profile and source it!'
-		  echo
-		  echo ' [[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"'
-		  echo
-		  echo "Maybe send me the file name and I'll look for it next time :)"
-		  echo
-		fi
-		[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
-	fi
+  if [ "$(whoami)" != "root" ]; then
+    if [ -e ~/.bashrc ]; then
+      cat ~/.bashrc | grep "\[\[ -s \"\$HOME/.gvm/scripts/gvm\" ]] && source \"\$HOME/.gvm/scripts/gvm\"" > /dev/null 2>&1
+      if [ $? -ne 0 ]; then
+        echo '[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"' >> $ENV_FILE
+      fi
+    else
+      echo 'This must be a Mac... put this line in you profile and source it!'
+      echo
+      echo ' [[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"'
+      echo
+      echo "Maybe send me the file name and I'll look for it next time :)"
+      echo
+    fi
+    [[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
+  fi
   echo "Installed GVM v$GVM_VERSION"
   echo "Please restart your terminal session"
 fi
