Check for tput

diff --git a/scripts/function/display_error b/scripts/function/display_error
--- a/scripts/function/display_error
+++ b/scripts/function/display_error
@@ -1,8 +1,13 @@
 display_error() {
-	tput sgr0
-	tput setaf 1
-	echo "ERROR: $1" >&2
-	tput sgr0
+	which tput &> /dev/null
+	if [[ "$?" == "0" ]]; then
+		tput sgr0
+		tput setaf 1
+		echo "ERROR: $1" >&2
+		tput sgr0
+	else
+		echo "ERROR: $1" >&2
+	fi
 	return 1
 }
 
