Clean up default component installs

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -72,30 +72,30 @@ install_go() {
 }
 
 install_gb() {
-	echo " * Installing gb..."
-	goinstall github.com/skelterjohn/go-gb/gb
-	if [[ $? -ne 0 ]]; then
-		echo "Failed to install gb"
-		exit 1
+	if [[ "$version" == "release.r60.3" ]]; then
+		echo " * Installing gb..."
+		goinstall github.com/skelterjohn/go-gb/gb > /dev/null 2>&1
+		if [[ $? -ne 0 ]]; then
+			echo "Failed to install gb"
+			return 1
+		fi
 	fi
 }
 
 install_goprotobuf() {
-	echo " * Installing goprotobuf..."
 	if [[ "$version" == "release.r60.3" ]]; then
-		goinstall goprotobuf.googlecode.com/hg/proto
+		echo " * Installing goprotobuf..."
+		goinstall goprotobuf.googlecode.com/hg/proto > /dev/null 2>&1
 		if [[ $? -ne 0 ]]; then
 			echo "Failed to install goprotobuf"
-			exit 1
+			return 1
 		fi
 		cd $GVM_ROOT/gos/$version/src/pkg/goprotobuf.googlecode.com/hg/compiler
 		make install > $GVM_ROOT/logs/$version-pb-compiler.log 2>&1
 		if [[ $? -ne 0 ]]; then
 			echo "Failed to install goprotobuf compiler"
-			exit 1
+			return 1
 		fi
-	else
-		echo "   Don't know how to install goprotobuf for $version"
 	fi
 }
 
@@ -112,7 +112,6 @@ main() {
 	install_gb
 	install_goprotobuf
 	cd $GO_INSTALL_ROOT && find . > manifest
-
 	tput sgr0
 }
 
