Print errors to stderr

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -2,7 +2,7 @@
 display_error() {
 	tput sgr0
 	tput setaf 1
-	echo "ERROR: $1"
+	echo "ERROR: $1" >&2
 	tput sgr0
 	exit 1
 }
