More environment changes

diff --git a/scripts/pkgset-create b/scripts/pkgset-create
--- a/scripts/pkgset-create
+++ b/scripts/pkgset-create
@@ -1,15 +1,14 @@
 #!/bin/bash
+if [[ $gvm_go_name == "" ]]; then
+  echo "ERROR: No Go version selected"
+  exit 1
+fi
+
 if [[ -n $1 ]]; then
-	CUR_VER=`readlink $GVM_ROOT/go | awk '{ n=split($1,path,"/"); print path[n] }'`
-	if [[ $CUR_VER == "" ]]; then
-		echo "ERROR: No Go version selected"
+  mkdir -p $GVM_ROOT/pkgsets/$gvm_go_name/$1
+  if [[ $? -ne 0 ]]; then
+		echo "ERROR: Could not create folder"
 		exit 1
-	else
-    mkdir -p $GVM_ROOT/pkgsets/$CUR_VER/$1
-    if [[ $? -ne 0 ]]; then
-			echo "ERROR: Could not create folder"
-			exit 1
-		fi
 	fi
 else
   echo "ERROR: Please specifiy the name"
diff --git a/scripts/pkgset-empty b/scripts/pkgset-empty
--- a/scripts/pkgset-empty
+++ b/scripts/pkgset-empty
@@ -1,13 +1,15 @@
 #!/bin/bash
-CUR_VER=`readlink $GVM_ROOT/go | awk '{ n=split($1,path,"/"); print path[n] }'`
-if [[ $CUR_VER == "" ]]; then
+if [[ $gvm_go_name == "" ]]; then
   echo "ERROR: No Go version selected"
   exit 1
-else
-  rm -rf $GVM_ROOT/pkgs/*
-  if [[ $? -ne 0 ]]; then
-    echo "ERROR: Could not delete package set files"
-    exit 1
-  fi
+elif [[ $gvm_pkgset_name == "" ]]; then
+  echo "ERROR: No Package set selected"
+  exit 1
+fi
+
+rm -rf $GVM_ROOT/pkgsets/$gvm_go_name/$gvm_pkgset_name/*
+if [[ $? -ne 0 ]]; then
+  echo "ERROR: Could not delete package set files"
+  exit 1
 fi
 
