Working on environments

diff --git a/scripts/pkgset-create b/scripts/pkgset-create
--- a/scripts/pkgset-create
+++ b/scripts/pkgset-create
@@ -1,17 +1,28 @@
 #!/bin/bash
-if [[ $gvm_go_name == "" ]]; then
-  echo "ERROR: No Go version selected"
-  exit 1
-fi
+display_error() {
+	tput sgr0
+	tput setaf 1
+	echo "ERROR: $1"
+	tput sgr0
+	exit 1
+}
 
-if [[ -n $1 ]]; then
-  mkdir -p $GVM_ROOT/pkgsets/$gvm_go_name/$1
-  if [[ $? -ne 0 ]]; then
-		echo "ERROR: Could not create folder"
-		exit 1
-	fi
-else
-  echo "ERROR: Please specifiy the name"
-  exit 1
-fi
+[[ $gvm_go_name != "" ]] || 
+	display_error "No Go version selected"
+
+[[ $1 != "" ]] || 
+	display_error "Please specifiy the name"
+
+[[ ! -f "$GVM_ROOT/enviroments/$gvm_go_name@$1" ]] || 
+	display_error "Packageset already exists!"
+
+mkdir -p $GVM_ROOT/pkgsets/$gvm_go_name/$1 ||
+	display_error "Could not create folder"
+cp $GVM_ROOT/environments/$gvm_go_name $GVM_ROOT/environments/$gvm_go_name@$1 ||
+	display_error "Could copy environment"
+echo "export gvm_pkgset_name=\"$1\"" >> $GVM_ROOT/environments/$gvm_go_name@$1 ||
+	display_error "Could not extend environment"
+echo "export GOPATH; GOPATH=\"$GVM_ROOT/pkgs/release.r60.3/$1:\$GOPATH\"" >> $GVM_ROOT/environments/$gvm_go_name@$1 ||
+	display_error "Could not extend environment"
+
 
diff --git a/scripts/pkgset-delete b/scripts/pkgset-delete
--- a/scripts/pkgset-delete
+++ b/scripts/pkgset-delete
@@ -1,17 +1,24 @@
 #!/bin/bash
-if [[ $gvm_go_name == "" ]]; then
-  echo "ERROR: No Go version selected"
-  exit 1
-fi
+display_error() {
+	tput sgr0
+	tput setaf 1
+	echo "ERROR: $1"
+	tput sgr0
+	exit 1
+}
 
-if [[ -n $1 ]]; then
-  rm -rf $GVM_ROOT/pkgsets/$gvm_go_name/$1
-  if [[ $? -ne 0 ]]; then
-    echo "ERROR: Could not delete package set"
-    exit 1
-  fi
-else
-  echo "ERROR: Please specifiy the name"
-  exit 1
-fi
+[[ $gvm_go_name != "" ]] || 
+	display_error "No Go version selected"
+
+[[ $1 != "" ]] || 
+	display_error "Please specifiy the name"
+
+[[ -d $GVM_ROOT/pkgsets/$gvm_go_name/$1 ]] || 
+	display_error "Packageset doesn't exist!"
+
+rm -rf $GVM_ROOT/pkgsets/$gvm_go_name/$1 ||
+	display_error "Could not delete package set"
+
+rm -rf $GVM_ROOT/environments/$gvm_go_name@$1 ||
+	display_error "Could not delete package set"
 
diff --git a/scripts/pkgset-empty b/scripts/pkgset-empty
--- a/scripts/pkgset-empty
+++ b/scripts/pkgset-empty
@@ -1,15 +1,16 @@
 #!/bin/bash
-if [[ $gvm_go_name == "" ]]; then
-  echo "ERROR: No Go version selected"
-  exit 1
-elif [[ $gvm_pkgset_name == "" ]]; then
-  echo "ERROR: No Package set selected"
-  exit 1
-fi
+display_error() {
+	tput sgr0
+	tput setaf 1
+	echo "ERROR: $1"
+	tput sgr0
+	exit 1
+}
 
-rm -rf $GVM_ROOT/pkgsets/$gvm_go_name/$gvm_pkgset_name/*
-if [[ $? -ne 0 ]]; then
-  echo "ERROR: Could not delete package set files"
-  exit 1
-fi
+[[ $gvm_go_name != "" ]] || 
+	display_error "No Go version selected"
+[[ $gvm_pkgset_name != "" ]] || 
+	display_error "No Package set selected"
+rm -rf $GVM_ROOT/pkgsets/$gvm_go_name/$gvm_pkgset_name/* ||
+  display_error "Could not delete package set files"
 
